apiVersion: apps/v1
kind: Deployment
metadata:
    name: reviews
spec:
    replicas: 3
    selector:
        matchLabels:
            app: reviews
    template:
        metadata:
            name: reviews
            labels:
                app: reviews
        spec:
            containers:
            - name: reviews
              image: danibachar/tester:latest
              env:
              env:
              - name: RETURN_VALUE
                value: "reviews"
              - name: DEPENDENCIES
                value: "{\n  \"destinations\" : [\n    {\n      \"target\": \"http://rating\",\n      \"request_payload_kb_size\": 50,\n      \"config\": {\n        \"memory_params\": {\n          \"duration_seconds\": 0.2,\n          \"kb_count\": 50\n        },\n        \"cpu_params\": {\n          \"duration_seconds\": 0.2,\n          \"load\": 0.2\n        }\n      }\n    }\n  ]\n}"
              ports:
              - name: http-port
                containerPort: 8081
              resources:
                  requests:
                      cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
    name: reviews
spec:
    type: LoadBalancer
    selector:
        app: reviews
    ports:
    - port: 31002
      nodePort: 31002
      targetPort: http-port
      protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: reviews-autoscaler
spec:
    scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: reviews
    minReplicas: 3
    maxReplicas: 50
    targetCPUUtilizationPercentage: 50
