apiVersion: apps/v1
kind: Deployment
metadata:
    name: be_cache
spec:
    replicas: 3
    selector:
        matchLabels:
            app: be_cache
    template:
        metadata:
            name: be_cache
            labels:
                app: be_cache
        spec:
            containers:
            - name: be_cache
              image: eydayan/tester:latest
              imagePullPolicy: Always # to conserve on pulling can change to not allways pull
              env:
              - name: RETURN_VALUE
                value: "be_cache"
              ports:
              - name: http-port
                containerPort: 8081
              resources:
                  requests:
                      cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
    name: be_cache
spec:
    type: LoadBalancer
    selector:
        app: be_cache
    ports:
    - port: 80
      nodePort: 31003
      targetPort: http-port
      protocol: TCP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: be_cache-autoscaler
spec:
    scaleTargetRef:
        apiVersion: autoscaling/v2beta2
        kind: Deployment
        name: be_cache
    minReplicas: 3
    maxReplicas: 50
    targetCPUUtilizationPercentage: 50
