apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cluster-api
  name: cluster-msvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cluster-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cluster-api
    spec:
      containers:
      - image: danibachar/cluster-msvc:latest
        imagePullPolicy: Always
        name: cluster-msvc-container
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-msvc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: cluster-api